In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import cv2
from scipy import signal
from PIL import Image

# lineCode
from lineCoding import unrz_l
from lineCoding import manchester

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
%cd "/content/drive/MyDrive/DataComm_Project"

In [ ]:
# Source random
img = np.random.randint(low=0, high=256, size=(2, 2, 3)).astype(np.uint8)
x,y,z=img.shape[0], img.shape[1], img.shape[2]
print(img.shape)
print(img)

(2, 2, 3)
[[[ 97 160 126]
  [249 235 251]]

 [[ 13 147 192]
  [141 116 152]]]


In [9]:
# Format data
binary_data = np.unpackbits(img, axis=2)
bitstream = binary_data.ravel()
print(bitstream.shape)
print(bitstream)

(96,)
[0 1 1 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 1 1 1 1 1 0 1 1 1 1 1 0 0 1 1 1 1 0 1
 0 1 1 1 1 1 1 1 0 1 1 0 0 0 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 0 0 0 0 0 0 1 0
 0 0 1 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0]


In [11]:
# prepare for encoding stage
amplitude = 5
t = 0.5
sampling_rate = 10
n = t*sampling_rate

In [12]:
# encode using uniporlar non-return to zero
signal = unrz_l.encode(bitstream, amplitude, n) 
print(signal.shape)
print(signal)

(480,)
[0. 0. 0. 0. 0. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 0. 0. 0.
 0. 0. 5. 5. 5. 5. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 0. 0. 0. 0. 0.
 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.
 5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5. 5. 0. 0. 0. 0. 0. 5. 5. 5. 5. 5. 0. 0. 0. 0. 0. 5. 5.
 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5. 5. 5. 5. 0. 0. 0. 0. 0. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5. 0. 0. 0. 0. 0. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5.
 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5

In [ ]:
# plot signal after urnz encode 
unrz_l.draw_signal(signal, amplitude, t, sampling_rate)
print(bitstream)

In [ ]:
# decode unrz_l
decode = unrz_l.decode(signal, n)
print(decode.shape)
print(decode)

In [ ]:
# convert 8 bits to 0-255 decimal
decode_dec = np.packbits(decode).reshape((x,y,z))
print("Result\n",decode_dec)
print("-----------------------")
print("Origin data\n", img)

In [ ]:
# convert 3D array to image
de_img = Image.fromarray(decode_dec)
print(decode_dec.shape)

# display the image
plt.imshow(de_img)
plt.show()